game/urls.py
from django.urls import path
from . import views

app_name = 'game'
urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('start_game', views.start_game, name = 'start_game'),
    path('game/<int:pk>/', views.GameView.as_view(), name = 'game'),
    path('make_move/<int:pk>/', views.make_move, name = 'make_move')
]

tictactoe_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
]

game/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
import numpy as np

# Create your models here.

def default_board(size = 3):
    """Will return an x*x board. Could be used to improve later to have default options, if desired."""
    return list([0] * (size*size))

class TicTacToe(models.Model):
    """From previously made python class TicTacToe, adapted to work as a Django class.
    Also based on the github page https://github.com/claudiordgz/tictactoe-django/blob/master/game/models.py
    which has been inspirational in building this app."""

    board = ArrayField(models.IntegerField(), default = default_board, size = 9,)
    total_moves = models.IntegerField(default = 0)
    player = models.IntegerField(default = 1)
    winner = models.CharField(max_length = 1, default = "N") #Can be N when in progress, D if drawn, or 1/2 for p1/2

    def make_move(self, move):
        """Make a move for each player, check its valid and victory condition.
        Moves can be 0 - 8 when input from web.
        """
        player = self.player
        if self.winner != "N":
            return
        try:
            self.update_board(player, move)
            self.total_moves += 1
            
            self.check_victory()
            if self.player == 1:
                self.player = 2
            else:
                self.player = 1
        except:
            ##Shouldn't be possible for user to fail, this is for testing purposes
            return "Failed"

    def update_board(self, player, move):

        ##TO DO: Update player aswell.
        """Updates the board when a valid move is made."""
        num = player
        if (self.board[move] == 0):
            self.board[move] = player
        else:
            Exception()
    
    def check_victory(self):

        ##TO DO: FIGURE OUT HOW TO WORK THIS NUMPY STUFF
        ##TO DO: CHANGE VICTORY TO AN ALTERATION OF THE MODEL FIELD.
        """Checks if victory condition of 3 in a row met."""
        check_board = np.zeros((3,3)) ##Update this to size if you change it
        for i in range(3):
            for j in range(3):
                check_board[i,j] = self.board[0+i*3 + j]
        for i in range(3):
            if ((np.all(check_board[i,:] == check_board[i,0])) 
                and (check_board[i,0] != 0)):
                    self.winner = str(self.player)
            if ((np.all(check_board[:, i] == check_board[0,i])) 
                and (check_board[0,i] != 0)):
                    self.winner = str(self.player)
        ##Also check diagonal
        if (((check_board[0,0] == check_board[1,1] == check_board[2,2])
            or (check_board[2,0] == check_board[1,1] == check_board[0,2]))
            and check_board[1,1] != 0):
            self.winner = str(self.player)
        else:
            if self.total_moves >= 9:
                self.winner = "D"

game/forms.py
from .models import TicTacToe
from django import forms

class InputForm(forms.Form):
    move = forms.IntegerField()

game/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic.base import View
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse

from .models import TicTacToe
from .forms import InputForm

class IndexView(View):
    """Show some summary stats about history of the naughts and crosses games, with a big ass new game button."""

    template = "game/index.html"

    def get(self, request):
        return render(request, self.template)

class GameView(View):
    """Play a game, will reload and update based on player moves.
    Request will include a form, which will either have a valid move to add, or nothing (indicating a game has only just started)."""
    template = "game/game.html"

    def get(self, request, pk):
        game = get_object_or_404(TicTacToe, pk = pk)
        board = game.board
        status = game.winner
        player = game.player
        return render(request, self.template, {'id':pk, 'board':board, 'status':status, 'player':player})

def start_game(request):
    """Initialize a new game, and return it."""
    new_game = TicTacToe()
    new_game.save()
    new_id = new_game.id
    board = new_game.board
    return HttpResponseRedirect(reverse('game:game', args = (new_id,)))

def make_move(request, pk):
    game = get_object_or_404(TicTacToe, pk=pk)
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            player = game.player
            move = form.cleaned_data['move']
            # return HttpResponse(move)
            game.make_move(move)
            game.save()

            return HttpResponseRedirect(reverse('game:game', args = (game.id,)))
        else:
            raise Http404("Move was not valid and things went crazy")

game/templates/game/base.html
{% load static %}
<html>
    <head>
        <title>Tic-Tac-Toe</title>
        <link rel="stylesheet" type="text/css" href="{% static 'game/style.css' %}" />
    </head>
    <body>
        <div class="header">
            <h1>Tic Tac Toe!</h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                <form action = "{% url 'game:start_game' %}" method="post">
                    {% csrf_token %}
                    <input type = "submit" value = "Click Here to Start a New Game of Tic-Tac-Toe!">
                </form> 
                </div>
            </div>
        </div>
    </body>
</html>

game/templates/game/game.html
{% extends 'game/base.html' %}

{% block content %}

<div id = "game-status">
{% if status == "N" %}
    {% if player == 1 %}
        <p>It is player 1s turn (O's).</p>
    {% else %}
        <p>It is player 2s turn (X's).</p>
    {% endif %}
{% elif status == "1" %}
    <p>Player 1 has won the game!</p>
{% elif status == "2" %}
    <p>Player 2 has won the game!</p>
{% elif status == "D" %}
    <p>The game has ended in a draw.</p>
{% endif %}
</div>

<div class = "board">
{% for val in board %}
    {% if val == 0 %}
    <span class = "square playable" id = "square-{{ forloop.counter0 }}">
    <form action = "{% url 'game:make_move' id %}" method="POST">
        {% csrf_token %}
        <input name="move" value="{{ forloop.counter0 }}" type="hidden">
        <button type="submit">{{ next_player }}</button>
    </form>
    </span>

    {% else %}
    <span class = "square unplayable" id = "square-{{ val }}">
        {% if val == 1 %}
            <span>O</span>
        {% elif val == 2 %}
            <span>X</span>
        {% endif %}
    {% endif %}
    </span>

{% endfor %}
</div>

{% endblock %}

game/templates/game/index.html
{% extends 'game/base.html' %}

{% block content %}
{% endblock %}